/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 abstract_design.glb --transform
Author: cherkesgiller (https://sketchfab.com/cherkesgiller)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/abstract-design-5f61a7b5eaa64af093d7cd721c9ef5ad
Title: Abstract Design
*/

import React, { useRef, useLayoutEffect, useState } from 'react'
import { useAnimations, useGLTF, OrbitControls } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Oggetto3d(props) {

  const ref = useRef()
  const { nodes, materials, animations } = useGLTF('/abstract_design-transformed.glb');
  useFrame((state, delta) => (ref.current.rotation.x += 0.001))

  return (
<group {...props} dispose={null}>
      <mesh {...props} ref={ref} geometry={nodes.VoronoiDynoBake_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} position={ [0, -70, 0,] } scale={100} />
      </group>
  )
}

useGLTF.preload('/abstract_design-transformed.glb')
